In [1]:
import pandas as pd
import numpy as np

# 데이터 정제

In [2]:
# 1. DEG_Wilcoxon 전처리 
# Wilcoxon_DEG : Wilcoxon_DEG_~.csv

df_wilcoxon = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_Wilcoxon/Wilcoxon_DEG_mast_re.csv')
print(df_wilcoxon.shape)
print(df_wilcoxon.head())
df_wilcoxon = df_wilcoxon[["names", "logfoldchanges", "pvals", "pvals_adj"]]
df_wilcoxon.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "Wilcoxon_adj_pval"}, inplace=True)
print(df_wilcoxon.head())

(1274, 5)
     names     scores  logfoldchanges          pvals      pvals_adj
0  MT-ND4L  29.577090        2.949751  2.945506e-192  1.876287e-189
1     ACTB  28.513615        1.353704  7.942646e-179  3.372977e-176
2    HSPA8  26.594760        2.017142  7.804425e-156  1.988568e-153
3    RPS26  26.573017        2.572682  1.392319e-155  2.956356e-153
4   NFKBIZ  25.266998        1.964584  7.367272e-141  1.340844e-138
      gene  logfoldchanges           pval  Wilcoxon_adj_pval
0  MT-ND4L        2.949751  2.945506e-192      1.876287e-189
1     ACTB        1.353704  7.942646e-179      3.372977e-176
2    HSPA8        2.017142  7.804425e-156      1.988568e-153
3    RPS26        2.572682  1.392319e-155      2.956356e-153
4   NFKBIZ        1.964584  7.367272e-141      1.340844e-138

In [3]:
df_wilcoxon.head(2)

      gene  logfoldchanges           pval  Wilcoxon_adj_pval
0  MT-ND4L        2.949751  2.945506e-192      1.876287e-189
1     ACTB        1.353704  7.942646e-179      3.372977e-176

In [4]:
# 2. DEG_limatrend 전처리 
# limatrend_DEG : limmatrend_DEG_~.csv

df_limmatrend = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_limmatrend/limmatrend_DEG_mast_re.csv')
print(df_limmatrend.shape)
print(df_limmatrend.head(2))
df_limmatrend = df_limmatrend[["names", "logfoldchanges", "pvals", "pvals_adj"]]
print((df_limmatrend.head()))
df_limmatrend.rename(columns={"names": "gene", "pvals": "pval","pvals_adj": "limmatrend_adj_pval"}, inplace=True)
print(df_limmatrend.head())

(1274, 6)
     names          pvals      pvals_adj  logfoldchanges  neglog10_pvalue  \
0  MT-ND4L  4.940656e-324  4.940656e-324       -1.237962              NaN
1     JUND  9.595238e-292  6.112167e-289        1.409539       291.017944

   neglog10_adjpvalue
0                 NaN
1          288.213805
     names  logfoldchanges          pvals      pvals_adj
0  MT-ND4L       -1.237962  4.940656e-324  4.940656e-324
1     JUND        1.409539  9.595238e-292  6.112167e-289
2    RPS10        0.994670  4.761006e-246  2.021840e-243
3    RPLP0       -0.958098  6.531369e-236  2.080241e-233
4    RPS26       -1.083726  1.309729e-234  3.337189e-232
      gene  logfoldchanges           pval  limmatrend_adj_pval
0  MT-ND4L       -1.237962  4.940656e-324        4.940656e-324
1     JUND        1.409539  9.595238e-292        6.112167e-289
2    RPS10        0.994670  4.761006e-246        2.021840e-243
3    RPLP0       -0.958098  6.531369e-236        2.080241e-233
4    RPS26       -1.083726  1.309729e-234        3.337189e-232

In [5]:
df_limmatrend.head(2)

      gene  logfoldchanges           pval  limmatrend_adj_pval
0  MT-ND4L       -1.237962  4.940656e-324        4.940656e-324
1     JUND        1.409539  9.595238e-292        6.112167e-289

In [6]:
# 3. RISCQP_DEG 전처리
# DEG_RISCQP : RISCQP_DEG_-.csv

df_RISCQP = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_RISCQP/RISCQP_DEG_mast_re.csv')
print(df_RISCQP.shape)
print(df_RISCQP.head())
df_RISCQP = df_RISCQP[["Symbol", "log2FC", "Pvalue", "Padj"]]
df_RISCQP.rename(columns={"Symbol": "gene","Pvalue": "pval","Padj": "RISCQP_adj_pval"}, inplace=True)
print(df_RISCQP.head())

(1274, 10)
  Unnamed: 0   Symbol  Percent  Pct.Ctl  Pct.Sam  avelog.Ctl  avelog.Sam  \
0    MT-ND4L  MT-ND4L    0.576    0.380    0.946    7.367503    2.860963
1       JUND     JUND    0.679    0.836    0.380    2.743910    6.722146
2      RPS26    RPS26    0.581    0.410    0.904    7.022013    3.092824
3    MT-ATP8  MT-ATP8    0.326    0.147    0.664    4.891385    1.069644
4      RPS10    RPS10    0.447    0.649    0.066    0.463789    5.055815

     log2FC         Pvalue           Padj
0 -6.585650  1.897191e-177  2.417021e-174
1  5.833552  7.668164e-156  4.884620e-153
2 -5.734325  7.040593e-142  2.989905e-139
3 -6.109052  2.524673e-141  8.041083e-139
4  8.045777  1.047459e-131  2.668925e-129
      gene    log2FC           pval  RISCQP_adj_pval
0  MT-ND4L -6.585650  1.897191e-177    2.417021e-174
1     JUND  5.833552  7.668164e-156    4.884620e-153
2    RPS26 -5.734325  7.040593e-142    2.989905e-139
3  MT-ATP8 -6.109052  2.524673e-141    8.041083e-139
4    RPS10  8.045777  1.047459e-131    2.668925e-129

In [7]:
df_RISCQP.head(2)

      gene    log2FC           pval  RISCQP_adj_pval
0  MT-ND4L -6.585650  1.897191e-177    2.417021e-174
1     JUND  5.833552  7.668164e-156    4.884620e-153

In [8]:
# 4. monocle_deg 전처리
# DEG_monocle : monocle_DEG_-.csv

df_monocle = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_monocle/monocle_DEG_mast.csv')
print(df_monocle.shape)
print(df_monocle.head())
df_monocle = df_monocle[["gene", "log2FC", "pvalue", "adjpvalue"]]
df_monocle.rename(columns={"pvalue": "pval","adjpvalue": "monocle_adj_pval"}, inplace=True)
print(df_monocle.head())

(1274, 13)
   Unnamed: 0     gene  num_cells_expressed  gene_id status      term  \
0           1    TPSD1                 1569    TPSD1     OK  GroupMSI
1           2     JUND                 2094     JUND     OK  GroupMSI
2           3  MT-ND4L                 1777  MT-ND4L     OK  GroupMSI
3           4  MT-ATP8                 1006  MT-ATP8     OK  GroupMSI
4           5     RGS1                 1792     RGS1     OK  GroupMSI

     log2FC   std_err   test_val         pvalue  normalized_effect  \
0  0.906451  0.036447  24.870608  1.547920e-136           1.295360
1 -1.446904  0.058428 -24.763940  2.194219e-135          -2.059684
2  0.919347  0.038689  23.762662  8.128870e-125           1.313135
3  1.156936  0.061631  18.771954   1.280870e-78           1.628375
4 -1.014167  0.055131 -18.395565   1.425679e-75          -1.441948

  model_component      adjpvalue
0           count  1.972050e-133
1           count  2.793241e-132
2           count  1.033992e-121
3           count   1.627985e-75
4           count   1.810612e-72
      gene    log2FC           pval  monocle_adj_pval
0    TPSD1  0.906451  1.547920e-136     1.972050e-133
1     JUND -1.446904  2.194219e-135     2.793241e-132
2  MT-ND4L  0.919347  8.128870e-125     1.033992e-121
3  MT-ATP8  1.156936   1.280870e-78      1.627985e-75
4     RGS1 -1.014167   1.425679e-75      1.810612e-72

In [9]:
df_monocle.head(2)

    gene    log2FC           pval  monocle_adj_pval
0  TPSD1  0.906451  1.547920e-136     1.972050e-133
1   JUND -1.446904  2.194219e-135     2.793241e-132

In [10]:
# 5. DEG_MAST 전처리 
# MAST_DEG : MAST_DEG_~.csv

df_MAST = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_MAST/MAST_DEG_mast_cell.csv')
print(df_MAST.shape)
print(df_MAST.head(2))
# df_MAST = df_MAST[["names", "logfoldchanges", "pvals", "pvals_adj"]]
# print((df_MAST.head()))
df_MAST.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "MAST_adj_pval"}, inplace=True)
print(df_MAST.head())

(1274, 4)
     names  logfoldchanges          pvals      pvals_adj
0    RPS29        0.985891  2.549379e-320  3.247909e-317
1  MT-ND4L       -1.236665  2.094219e-296  1.334017e-293
      gene  logfoldchanges           pval  MAST_adj_pval
0    RPS29        0.985891  2.549379e-320  3.247909e-317
1  MT-ND4L       -1.236665  2.094219e-296  1.334017e-293
2    RPL41        0.606631  9.524892e-294  3.639979e-291
3     JUND        1.408842  1.142851e-293  3.639979e-291
4   MT-ND3        0.476219  7.296053e-274  1.859034e-271

In [11]:
df_MAST.head(2)

      gene  logfoldchanges           pval  MAST_adj_pval
0    RPS29        0.985891  2.549379e-320  3.247909e-317
1  MT-ND4L       -1.236665  2.094219e-296  1.334017e-293

## <font color="red">**MSS/MSI 데이터프레임**

In [12]:
import pandas as pd
from functools import reduce

# 1) 미리 각 df에서 gene + adj_pval 컬럼만 추출
dfs = [
    df_wilcoxon[["gene", "Wilcoxon_adj_pval"]],
    df_limmatrend[["gene", "limmatrend_adj_pval"]],
    df_RISCQP[["gene", "RISCQP_adj_pval"]],
    df_MAST[["gene", "MAST_adj_pval"]],
    df_monocle[["gene", "monocle_adj_pval"]],
]

# 2) Reduce를 이용해 순차적으로 outer merge
df_mmm = reduce(
    lambda left, right: pd.merge(left, right, on="gene", how="outer"),
    dfs
)

# 결과 확인
print(df_mmm.shape)
print(df_mmm.head())

(1274, 6)
     gene  Wilcoxon_adj_pval  limmatrend_adj_pval  RISCQP_adj_pval  \
0   ABCA1       9.022419e-09         6.830751e-15     8.492968e-07
1   ABCC4       2.906029e-01         4.861607e-01     7.720716e-01
2  ABRACL       3.455194e-01         8.003738e-02     9.905947e-01
3  ACADVL       2.340618e-01         2.459992e-01     2.876882e-01
4   ACAP2       1.522371e-06         5.563154e-12     3.555441e-07

   MAST_adj_pval  monocle_adj_pval
0   3.794689e-20          0.265331
1   1.628810e-02          1.000000
2   2.596271e-06          0.004154
3   4.658632e-01          1.000000
4   5.234597e-14          0.560535

In [13]:
df_mmm.head(2)

,gene,Wilcoxon_adj_pval,limmatrend_adj_pval,RISCQP_adj_pval,MAST_adj_pval,monocle_adj_pval
0,ABCA1,9.022419e-09,6.830751e-15,8.492968e-07,3.794689e-20,0.265331
1,ABCC4,2.906029e-01,4.861607e-01,7.720716e-01,1.628810e-02,1.000000

In [14]:
# 1) 각 컬럼별 rank 계산 (값이 작을수록 1위, NaN은 가장 마지막)
df_mmm['rank_wilcoxon'] = df_mmm['Wilcoxon_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_limma'] = df_mmm['limmatrend_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_RISCQP'] = df_mmm['RISCQP_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_MAST'] = df_mmm['MAST_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_monocle'] = df_mmm['monocle_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

# 2) 5개 rank의 합 계산
df_mmm['rank_sum'] = df_mmm[
    ['rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST', 'rank_monocle']
].sum(axis=1)

# 3) sum_rank 기준으로 정렬
df_mmm = df_mmm.sort_values('rank_sum').reset_index(drop=True)

# 결과 확인 (선택사항)
df_mmm

,gene,Wilcoxon_adj_pval,limmatrend_adj_pval,RISCQP_adj_pval,MAST_adj_pval,monocle_adj_pval,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,rank_monocle,rank_sum
0,MT-ND4L,1.876287e-189,4.940656e-324,2.417021e-174,1.334017e-293,1.033992e-121,2,1,1,2,3,9
1,JUND,8.190582e-222,6.112167e-289,4.884620e-153,3.639979e-291,2.793241e-132,1,2,2,3,2,10
2,RPS10,4.947934e-173,2.021840e-243,2.668925e-129,8.710252e-270,3.847828e-71,4,3,5,7,6,25
3,RPS26,2.956356e-153,3.337189e-232,2.989905e-139,6.533022e-212,1.326627e-65,6,5,3,16,10,40
4,RPLP0,1.163808e-127,2.080241e-233,6.045449e-111,2.526046e-226,1.670539e-64,10,4,8,13,11,46
...,...,...,...,...,...,...,...,...,...,...,...,...
1269,ARL5B,8.391213e-01,9.072915e-01,8.784934e-01,5.712503e-01,1.000000e+00,1223,1251,1239,1242,506,5461
1270,HINT1,9.962413e-01,8.568558e-01,7.368273e-01,8.981423e-01,1.000000e+00,1273,1239,1203,1264,506,5485
1271,SLC1A5,7.446904e-01,9.308998e-01,9.603282e-01,9.419856e-01,1.000000e+00,1189,1259,1267,1266,506,5487
1272,DDAH2,8.316907e-01,9.351384e-01,8.423355e-01,9.594946e-01,1.000000e+00,1220,1263,1229,1273,506,5491
1273,ROMO1,8.501637e-01,9.213955e-01,9.439293e-01,9.556236e-01,1.000000e+00,1227,1256,1259,1271,506,5519

In [15]:
df_mmm_re = df_mmm[['rank_sum', 'gene', 'rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST']]
df_mmm_re.head(20)

    rank_sum      gene  rank_wilcoxon  rank_limma  rank_RISCQP  rank_MAST
0          9   MT-ND4L              2           1            1          2
1         10      JUND              1           2            2          3
2         25     RPS10              4           3            5          7
3         40     RPS26              6           5            3         16
4         46     RPLP0             10           4            8         13
5         49     HSPA8              5           6           14         15
6         56   MT-ATP8             12           9            4         27
7         75     TPSD1              8          14            7         45
8         84    NFKBIZ              7          11           17         33
9         93     RPL10             30           8           26         14
10        99      CD81             16          20           16         34
11       101     RPL29             33          10            9         26
12       107    RPS4Y1             22          17           10         50
13       113      ACTB              3           7           42          9
14       119     RPL28             46          13            6         28
15       137   ATP6V0C             21          32           11         53
16       143    RPL27A             11          21           74         19
17       144    MAP3K8             24          23           24         59
18       157  PPP1R15A             15          15           50         40
19       165      RGS1             20          40           32         68

In [16]:
# 원하는 순서의 리스트
genes_of_interest = ["VSIG4", "LYVE1", "CLEC5A", "CX3CR1", "FN1", "IL11", "NRAP", "SDC1", "SCG5"]
df_mmm_re_filtered = df_mmm_re[df_mmm_re["gene"].isin(genes_of_interest)]
df_mmm_re_filtered

Empty DataFrame
Columns: [rank_sum, gene, rank_wilcoxon, rank_limma, rank_RISCQP, rank_MAST]
Index: []